<?php

/**
 * @file
 * Pathauto alias handling for multiple domains.
 */

use Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException;
use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function domain_path_pathauto_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['path']['widget']) && ($object = $form_state->getFormObject()) && is_callable([
    $object,
    'getEntity',
  ])
    && ($entity = $object->getEntity())) {
    $domain_path_helper = \Drupal::service('domain_path.helper');
    $domain_path_pathauto_helper = \Drupal::service('domain_path_pathauto.helper');
    /** @var \Drupal\domain_path_pathauto\DomainPathautoHelper $domain_path_pathauto_helper */
    if ($domain_path_helper->domainPathsIsEnabled($entity)) {
      try {
        $domain_path_pathauto_helper->alterEntityForm($form, $form_state, $entity);
      }
      catch (InvalidPluginDefinitionException | PluginNotFoundException $e) {
      }

    }
  }
}
